# Generated by Django 4.0 on 2022-06-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day16', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deparment',
            name='ID',
            field=models.IntegerField(default=1, verbose_name='ID号'),
            preserve_default=False,
        ),
    ]
